### ISSUE TITLE
MFXButton ripples outside of button when setting -fx-background-radius

### ISSUE THREAD

**Issue by euseanwoon2016** [palexdev/MaterialFX#107]
I'm not sure if I'm doing this correctly, but when I set the `-fx-background-radius` value to something high, the ripples go outside the button.

![image](https://user-images.githubusercontent.com/20278298/136150389-ba88abae-11a4-4075-b8b1-8fcad9c7223b.png)

I might be doing this wrong but I don't see any way to change it in the button wiki page.

**Comment by palexdev** [comment]
As of now the wiki's purpose is just to list the properties of my new controls, also it's outdated since I haven't had any time to review it, but I will do with the next release

As for your issue:
The ripple generator clips itself to avoid ripples going out of the node's bounds, by default the clip is a rectangle with width and height equal to the node's ones.
(You can even remove the clip on purpose, the system is actually pretty flexible)
So basically if you're node is not a perfect rectangle you'll have to specify the clip for the ripple generator.

You can check an example here: [MFXRectangleToggleNode](https://github.com/palexdev/MaterialFX/blob/cf85498dcaa69ef41c830910e8537b39b02ff0f9/materialfx/src/main/java/io/github/palexdev/materialfx/controls/MFXRectangleToggleNode.java#L78)

Note that the node's radius is 10 and the clip arcs are set to 15. You'll have to "fine-tune" the clip factory so that the clip is perfectly shown

Anyway, I should add an example in the documentation, although the IRippleGenerator interface already documents this behavior

**Comment by euseanwoon2016** [comment]
Is this the best way to go about it?

```java
public class MFXPillButton extends MFXButton {
    @Override
    protected void setupRippleGenerator() {
        super.setupRippleGenerator();

        getRippleGenerator().setClipSupplier(() -> new RippleClipTypeFactory(RippleClipType.ROUNDED_RECTANGLE).setArcs(40).build(this));
    }
}

```

I find that the value of `-fx-background-radius` is not at all close to what the arc's values should be. Do I have to play around with the values till I find the correct one or is there some type of calculation?

Thanks.

**Comment by palexdev** [comment]
It seems to work, ok the right side the ripple doesn't overflow
Ok the left side it doesn't reach, if you are referring to that than there are several ways to make the ripple bigger

As for the radius-arcs values, tipically the arcs' value is 1.5 times the value of the radius. This is a starting point though, you'll have to experiment with values

**Comment by euseanwoon2016** [comment]
> On the left side it doesn't reach, if you are referring to that than there are several ways to make the ripple bigger

Oh sorry, this was because I took a screenshot before it reached the end. It manages to reach the end actually.



> As for the radius-arcs values, tipically the arcs' value is 1.5 times the value of the radius. This is a starting point though, you'll have to experiment with values

Alright, thanks for this! I shall play around with the values.

This solved my problem. Thanks very much.
