### ISSUE TITLE
Dude at least make introductory video that how to run first javaFX program with materialFX

### ISSUE THREAD

**Issue by Rakib-Hasan-455** [palexdev/MaterialFX#130]
Dear Developers,
I have been struggling to figure out how can I run MaterialFX for hours. But there is 0 tutorial video of MaterialFX on the internet. Even I am stuck and have no other solution video. As a beginner of MaterialFX, it's pretty confusing.
However, I don't know why the JavaFX program not working or running though I have added the MaterialFX dependency in Maven.
Showing error again and again :) . 
SS of error  -> <a href="https://imgur.com/a/xLD4Bqj"> Image Link </a>
Error full text -> <a href="https://pastebin.ubuntu.com/p/k78nGy96qg"> Full text </a>

**Comment by palexdev** [comment]
1) There is no tutorial because there's no need. It's easy to add MaterialFX to your projects, instructions are already there in the README
2) Your are not only a beginner to MaterialFX but probably to Java too, since anyone with a fair knowledge of Java and its build systems would have no issues whatsoever to make MaterialFX and any other Java library work. And to be honest I'm starting to get tired of this.
3) The error says it cannot find the MFXButton class. If it is a modular project, and I believe it is, did you add the 'require' statement in the module-info.java?
