### ISSUE TITLE
MFXTablecolumn can't attach to MFXLegacyTableView in Scenebuilder 17

### ISSUE THREAD

**Issue by Roccoxx** [palexdev/MaterialFX#165]
Hi, i have problemn with the MFXTablecolumn, i can't add MFXTablecolumn  to MFXLegacyTableView  or default TableView but yes to other elements for example a button or a TableColumn:

![image](https://user-images.githubusercontent.com/53314419/158880875-0c465495-4245-43cb-96cd-e1eb43cac410.png)

**Comment by palexdev** [comment]
@Roccoxx Unfortunately this can't be fixed.
You see SceneBuilder is made by JavaFX devs so there are some special controls that are handled "specially" by SceneBuilder.

TableColumns are one of them. In general when you drag a node on a Pane, it is added to the Pane's children list, that's how SceneBuilder works. Columns are handled differently, when they are dropped on a TableView they are added to the column's list not the children.
That's why there's no way to tell SceneBuilder to add MFXTableColumns to my table views, I'm really sorry for this but that's how they made the tool.
