### ISSUE TITLE
MFXTextField doesn't accept "On Key Pressed"

### ISSUE THREAD

**Issue by MohamadShaheen** [palexdev/MaterialFX#183]
I've realized that MFXTextField doesn't do what is required for "On Key Pressed". However, this can be replaced with "On Key Released" but I don't think that this is a good solution since for sequential writing the program will do nothing until the key is released.

I hope for help if anyone knows a solution for this or to fix this BUG ASAP.

All the best.

**Comment by Tech-Expert-Wizard** [comment]
I found that if you press the "enter" key it works. Basically, there's a workaround for this.
```java
yourField.textProperty().addListener((ObservableValue<? extends String> ov, String old, String nw) -> System.out.println("abc"));
```
But you still need the usual onKeyPress event handler because, for some reason, onKeyPress works for keys that do not add text into the field, like "enter." Of course, if you don't need to monitor a key like "enter," then you don't need the onKeyPress event handler.

**Comment by palexdev** [comment]
The thing is MFXTextField is just a wrapper for an original TextField. This is the only viable way to deeply customize the text field in JavaFX because making it from scratch would be utter madness.
So, as you can read in from the Javadocs, MFXTextFields offers some methods to directly interface to the original text filed (the delegate methods)
As for the event handling it's the same thing. MFXTextField does absolutely nothing, all the events are still on the original text field wich means the only way to catch them is to use event filters in some cases
I don't think it's really an issue though so, I'm closing this.

**Comment by viljanvr** [comment]
> For some reason, using an event filter instead of an event handler works.
> 
> ```java
> field.addEventFilter(KeyEvent.KEY_PRESSED, e -> System.out.println("abc"));
> ```

There is still a problem when using an eventFilter, because you'll get the event before it's consumed by the inner TextField. And therefore, the inner Textfield's value will be updated after your eventHandle is run. This is a problem when you want to get the text from the textfield in your eventHandle method. 

I still haven't found solution to this problem.

**Comment by palexdev** [comment]
The whole point was to avoid exposing the real field to the user because from a developing standpoint it's just the right thing to do in my opinion

But at this point I think the best think would be to expose it and let the user do what he wants
The disclaimer of course would be that I'm not responsible for any misuse/issue, I think that's only fair

In the end though the very best case would be to make the TextField from scratch, that would be a really great achievement for me as a developer and for the user as many new features would be better integrated
I'll think about this
