### ISSUE TITLE
Left top corner is inoperable

### ISSUE THREAD

**Issue by Yao-0x1e** [palexdev/MaterialFX#213]
Hi, I cloned this project and started the demo with command './gradlew run'. However, I found that the top left corner of my screen was covered by a transparent box or something?  When the demo application is set on top, anything on the area, as described below, is inoperable.

![2022-06-03_16-26](https://user-images.githubusercontent.com/61866196/171819125-2ccd7ee4-fb31-4b35-9e8e-c0c996f8d5e0.png)

My OS is Ubuntu 22.04 LTS and the OpenJDK version that I am using is 17.

**Comment by palexdev** [comment]
Yes this is a known issue of the notification systems
They are automatically initialized by the demo but the bug is not present in MaterialFX as long as the systems are not initialized

The "hidden box" is a transparent, empty stage so that notifications always have an owner and can be easily shown on the screen without too much hassle

Although I remade the system in v11.13.0 I think I'll remake it once again. I'm not satisfied but to be honest it's quite hard to make a good notification system

**Comment by palexdev** [comment]
Oh since you're a Linux-mate I have a question for you
When you run the demo do you also see more than one window open in the taskbar?

If yes then It should confirm the bug I mentioned above they are the hidden stage and I suspect it is a Linux specific bug since I don't remember it happening on Windows

**Comment by Yao-0x1e** [comment]
> Yes this is a known issue of the notification systems They are automatically initialized by the demo but the bug is not present in MaterialFX as long as the systems are not initialized
> 
> The "hidden box" is a transparent, empty stage so that notifications always have an owner and can be easily shown on the screen without too much hassle
> 
> Although I remade the system in v11.13.0 I think I'll remake it once again. I'm not satisfied but to be honest it's quite hard to make a good notification system
> 
> P.S.: don't close this issue please, i want to keep this open as a reminder

It's true, I removed the code in the construct function of **NotificationController** and this problem disappeared. Is there a compromised solution for this problem at this time, regardless of performance, since I have used the NotificationSystem in my project.

**Comment by palexdev** [comment]
Fixed in version `11.17.0`
