### ISSUE TITLE
Restrictive license

### ISSUE THREAD

**Issue by JonathanVusich** [palexdev/MaterialFX#22]
Would you consider relicensing this project to be more permissive? Something like the MIT license or Apache 2.0 license would be wonderful. I mention this because I am unable to use this project with the current GPL 3.0 license.

**Comment by palexdev** [comment]
Which point of the [GNU GPL](https://choosealicense.com/licenses/gpl-3.0/) license is limiting you exactly?

**Comment by JonathanVusich** [comment]
GPL code cannot easily be used in proprietary software. I would like to try out this library, but I don't want to put in the effort if it cannot be used in commercial products as well as open source products.

**Comment by palexdev** [comment]
I can't do that. The thing is I was not kidding in the README when I said that I'm putting a lot of effort in this project so I want credits for my work.
Also if someone wants to modify the project, the source code must be available to everyone since it may be useful for other users.
So, what I can do is switch to LGPL which still require you to release the library source code with all the changes made to it but doesn't require you to release the entire app source code.

**Comment by JonathanVusich** [comment]
Ultimately the licensing decision is totally up to you! I don't think I will be using this library over JFoenix given that JFoenix has a more permissive license and a longer track record. But kudos to you for putting in the effort, and I will keep an eye on this project as time goes on.

**Comment by palexdev** [comment]
As I said all I can do is switch to LGPL, if that's not enough then use whatever meets your requirements.
Closing the issue, but feel free to re-open it if you have anything to add.
