### ISSUE TITLE
Issue - MFXTableView 

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#24]
Big tables should be scrollable
if you set in maxRowsCombo big integer the table will go out of the scene borders
the excepted result should be scrollable table with pagination

**Comment by palexdev** [comment]
This is the intended behavior. You have two choices: 1) Wrap the table in a scroll pane. 2) Set maxRowsCombo to a reasonable value and then adjust the table's container/pane so that it will never go out of borders.
There's the intention to create a scrollable table view but don't expect it in the near future as there are a bunch of improvements and bug fixes I'm working on right now, a new minor version will be available soon.

**Comment by Ev1dentSnow** [comment]
Is there a way to restrict the overall width of a tableview from exceeding a certain width no matter how many columns there are?

**Comment by palexdev** [comment]
![image](https://user-images.githubusercontent.com/16880178/145200766-dcfed62b-085e-4b82-a00e-f1d583ae7c0c.png)
It's happening....hahaha
The scrolling is limited to vertical only at the moment though

**Comment by palexdev** [comment]
New tables available in latest release
