### ISSUE TITLE
Problem with setRowCellFactory  method

### ISSUE THREAD

**Issue by Alberto091998** [palexdev/MaterialFX#289]
Hello! can i write the setRowCellFactory method for this object to write in Table?

Object for The Table:
![image](https://user-images.githubusercontent.com/126072467/220605383-9f5441f4-5bf3-454a-b2a2-539a4d58a5bd.png)
Method in Controller class:
![image](https://user-images.githubusercontent.com/126072467/220605611-5eacc299-4b42-4574-b6a3-449236b554e6.png)
Expected Result:
![image](https://user-images.githubusercontent.com/126072467/220606580-76793ac6-78ea-422c-aa33-6722fccd946f.png)
Actual Result:
![image](https://user-images.githubusercontent.com/126072467/220606669-9f858884-70e7-4b7d-8fc1-28c57fe03341.png)

**Comment by palexdev** [comment]
You can't create columns in a for loop, each column needs it's own row cell factory 
It's the second line of code in the loop that is responsible for how data is extracted and visualized

**Comment by Alberto091998** [comment]
thank you for your response!

i read the header and values from Excel File with Apache POI Library and incapsulate the whole in ExcelForViewReport Object.

i need to display the ExcelForViewReport Object in table.

how could I do this?

Sorry for my bad english but i am italian

**Comment by palexdev** [comment]
Do you have any experience with JavaFX though?
Because now that I see it better, there actually are two fatal issues here.
1) Is what I already said, you are not creating columns and row cell factories in the correct way for your model
2) This piece of code is wrong:
```java
for (List<String> row : rowValues) {
    excelTable.setItems(FXCollections.observableArrayList(row);
}
```
The result of such code is that your table will always display only the last row of values because you are not adding them but replacing at each iteration.


To fix it without changing the `ExcelForViewReport` object, your model, is to change the table and how columns are set up.

1) For the table, you want something like this:
```java
MFXTableView<List<String>> table = ...;
table.setItems(FXCollections.observableArrayList(model.getRowValues()));
```

2) For the columns, I'm going to write a general example on how to write them below:
```java
MFXTableColumn<List<String>> column = new MFXTableColumn(name, true);
column.setRowCellFactory(list -> new MFXTableRowCell<>(l -> l.get(i)));
// Replace 'i' with index at which the data for the column is stored in the given list 'l'
```

3) Add all the created columns to the table:
```java
table.getTableColumns().addAll(...);
```

**Comment by Alberto091998** [comment]
Thank you!

I succeeded with your solution!

I'm new to JavaFX and I still have a lot to learn.

I'm migrating from Swing Library

**Comment by palexdev** [comment]
Good, make sure to watch some examples then, they can prove to be very helpful
Many of them are available in the demo source code
