### ISSUE TITLE
MFXTableView Cell Editable

### ISSUE THREAD

**Issue by Alberto091998** [palexdev/MaterialFX#290]
Hello!

Is there a way to change the value of cells using the MFXTableView object?

thank you for response!

**Comment by palexdev** [comment]
Not by default
The easiest way to do this would be to create a custom Skin for MFXTableRowCell which uses a text field instead of a Label to show/edit the content. 
Then when using `setRowCellFactory(...)` you'd have to create an anonymous class which overrides the `createDefaultSkin()` method to use the custom Skin

Bonus for appeal.
You could also just extend the existing Skin implementation and just add the field on top of the Label, then add handling when doble clicking (for example, can be any event you want) show the field for the edit, when confirming the edit or on focus lost hide the field and show the Label again.
It's more elaborate but also more appealing.

**Comment by Alberto091998** [comment]
Good Morning!

In this image, the body of the table population method.
![image](https://user-images.githubusercontent.com/126072467/220857829-eae4db25-be5e-456e-8b92-9c308456ce70.png)

Should there be an object that extends MFXTableRowCellSkin<T, E> instead of CustomSkin?

thank you for response!

**Comment by palexdev** [comment]
You want something like this:
```java
public class EditRowCellSkin<T, E> extends MFXTableRowCell<T, E> {
    // Add the features you need here
}
```

Then when using `setRowCellFactory(...)`
```java
MFXTableColumn<List<String>> column = ...;
column.setRowCellFactory(list -> new MFXTableRowCell<>(l -> l.get(index)) {
    @Override
    protected Skin<?> createDefaultSkin() {
        return new EditRowCellSkin<>(MFXTableRowCell.this);
    }
});
```
