### ISSUE TITLE
LabelFloat option for testfield is missing

### ISSUE THREAD

**Issue by j-razeed** [palexdev/MaterialFX#32]
Material's key feature label float for text field is missing.

https://material.io/components/text-fields#usage

**Comment by palexdev** [comment]
Yeah, I'm aware of this lack.
However, I'm not sure if I will ever implement that feature to JavaFX because the positioning can be quite tricky.

I'm going to flag this issue as an "enhancement", maybe I will consider it in the future, but it's a not high priority as we have an alternative which is the prompt text.

**Comment by Ulathar** [comment]
Would love to see this as well because I am running in more and more problems with JFoenix on more recent JDKs (10+, 11 especially). 
Currently trying some basic stuff with your great work considering to switch from JFoenix to MaterialFX but would really miss LabelFloat in my UI / would change the current "feel" quite a lot.

**Comment by AigleDev** [comment]
Any ETA ?

**Comment by palexdev** [comment]
> Any ETA ?

Unfortunately no, I can't give you any ETA.

Currently, I'm 100% focused on implementing my own VirtualFlow and ditch ReactFX once and for all
This also means that I will have to re-make the list views, the combo boxes and also the selection models (will be a huge update)
The good thing is that the VirtualFlow development is proceeding quite well.

Since many people seem to want this feature, I'll consider this as a top priority from now on, but still I can't promise anything on when it will be implemented

**Comment by Tech-Expert-Wizard** [comment]
@palexdev I actually made a custom label float MFXTextField by adding a label in VBox and using a focus listener, but it moves whenever I focus or unfocus the text field. I believe it would be possible to make it work by (somehow) predicting the size of the label and adding a padding of the same size and removing the padding and adding the label at focus.

**Comment by palexdev** [comment]
> @palexdev I actually made a custom label float MFXTextField by adding a label in VBox and using a focus listener, but it moves whenever I focus or unfocus the text field. I believe it would be possible to make it work by (somehow) predicting the size of the label and adding a padding of the same size and removing the padding and adding the label at focus. I will create a pull request if I successfully do this.

@Tech-Expert-Wizard thanks but I already did it  
It's on the staging branch 😉

**Comment by Tech-Expert-Wizard** [comment]
Thanks, I'll check the staging branch.

**Comment by palexdev** [comment]
Changes to text fields available in latest release
