### ISSUE TITLE
The MFXStageDialog  show method call is time consuming

### ISSUE THREAD

**Issue by vicasong** [palexdev/MaterialFX#328]
**Describe the bug**

I refer to the usage example of the dialog box and find that it is very slow to display the dialog box every time, at least waiting for more than one second.

**To Reproduce**
I have prepared a demo to reproduce the problem:  https://github.com/vicasong/mfx-dialogs-demo.git

**Expected behavior**
The dialog should be displayed with very low latency (up to a few hundred milliseconds) after calling the show method

**Environment**
Host OS: Windows 11 x64
JVM: Openjdk 17.0.7

![screenshots 2023-07-18 164922](https://github.com/palexdev/MaterialFX/assets/21325582/2af3e3b6-2e4b-4f65-a914-dad1a08c2473)

**Comment by vicasong** [comment]
I'm not familiar with java-fx, so is there a solution?

**Comment by palexdev** [comment]
There are a bunch of optimizations you could try:
1) Instantiate the MFXStageDialog before use, at the start of the app, for example
2) The delay should mostly be bacause of how Theming has changed is recent versions. You could try removing all the stylesheets from the dialog's content and just add the ones you need
More info on the issue here: #307

**Comment by palexdev** [comment]
Should have improved in version `11.17.0`
