### ISSUE TITLE
MFXRectangleToggleNode ignores graphic

### ISSUE THREAD

**Issue by warmuuh** [palexdev/MaterialFX#71]
might be intended but it seems counter-intuitive that MFXRectangleToggleNode ignores any graphic, if it is set. Example:

```java
var mfx = new MFXRectangleToggleNode();
mfx.setGraphic(icon(FontAwesomeIcon.GLOBE));
root.add(mfx);

JFXToggleNode node = new JFXToggleNode();
node.setGraphic(icon(FontAwesomeIcon.GLOBE));
root.add(node);


ToggleButton javafx = new ToggleButton();
javafx.setGraphic(icon(FontAwesomeIcon.GLOBE));
root.add(javafx);
```

results in 
![image](https://user-images.githubusercontent.com/1331628/125414483-a4aae56b-7e4e-4f73-b121-2ba5ad78657a.png)

using setLeading / Trailing icon fixes it, so it might be intentional though... 

using leading/trailing though results in non-centered icon (if empty text):
![image](https://user-images.githubusercontent.com/1331628/125415189-accbe255-39c8-4d27-977f-f653c8f44446.png)

**Comment by warmuuh** [comment]
created https://github.com/palexdev/MaterialFX/pull/72 to fix this. not sure if this is how you would do it but it works :D

**Comment by palexdev** [comment]
Thanks for the contribution, but that's not a good way to fix it.
It's the toggle node skin that must be modified, not the label, did you test what happens if a MFXLabel has all three icons set?
I didn't, but I think it would create a mess of overlapping graphics.

A viable solution is to keep track of the toggle's graphic property and prioritize it over the leading and trailing icons.
Fixed in the latest commit on staging

**Comment by palexdev** [comment]
New version released
