### ISSUE TITLE
no documentation on how to use the ripple effect ?

### ISSUE THREAD

**Issue by icyhoty2k** [palexdev/MaterialFX#76]
can you provide an example how to use the ripple effect 
i use 
       MFXCircleRippleGenerator ripple = new MFXCircleRippleGenerator (test2pane) ;
        testPane.getChildren().add(test2pane);
but it does not work

**Comment by palexdev** [comment]
There's no documentation because the ripple generator is used by many controls, so examples are everywhere.  
But I may consider adding it in the future.  

You can check the [MFXCheckboxSkin](https://github.com/palexdev/MaterialFX/blob/main/materialfx/src/main/java/io/github/palexdev/materialfx/skins/MFXCheckboxSkin.java) for example.  

In general you have a region on which you want to generate the ripple so the code would be:

```
Region region = ...
MFXCircleRippleGenerator generator = new MFXCircleRippleGenerator(region) // Needed to pass the region reference
generator.setRipplePositionFunction(mouseEvent -> ...) // This is to to specify where the ripple should be placed when generated
region.getChildren().add(generator) // Ripples are added to the generator's container so the generator must be added to the region
region.addEventHandler(MouseEvent.MOUSE_PRESSED, generator::generateRipple)
```

**Comment by palexdev** [comment]
Documentation added in latest release
